In [1]:
import pandas as pd
import numpy as np

#### df_33 : base de données contenant résultats des electionspar bureaux de vote  
#### geo_33 : base de données contenant les informations de coordonnées géographiques

In [2]:
df = pd.read_csv("../data/raw/PR17_BVot_T1_FE (copy).txt", encoding = "ISO-8859-1", sep =';', decimal =',')

df

/home/will/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (0,6) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Code du département,Libellé du département,Code de la circonscription,Libellé de la circonscription,Code de la commune,Libellé de la commune,Code du b.vote,Inscrits,Abstentions,% Abs/Ins,...,Voix.9,% Voix/Ins.9,% Voix/Exp.9,N°Panneau.10,Sexe.10,Nom.10,Prénom.10,Voix.10,% Voix/Ins.10,% Voix/Exp.10
0,1,Ain,4,4ème circonscription,1,L'Abergement-Clémenciat,0001,598,92,15.38,...,6,1.00,1.21,11,M,FILLON,François,110,18.39,22.22
1,1,Ain,5,5ème circonscription,2,L'Abergement-de-Varey,0001,209,25,11.96,...,1,0.48,0.57,11,M,FILLON,François,34,16.27,19.32
2,1,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,0001,1116,233,20.88,...,7,0.63,0.81,11,M,FILLON,François,116,10.39,13.49
3,1,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,0002,1128,256,22.70,...,11,0.98,1.29,11,M,FILLON,François,124,10.99,14.59
4,1,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,0003,1116,227,20.34,...,7,0.63,0.80,11,M,FILLON,François,149,13.35,17.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69237,ZZ,Français établis hors de France,11,11ème circonscription,226,Wuhan,1,369,129,34.96,...,3,0.81,1.27,11,M,FILLON,François,62,16.80,26.27
69238,ZZ,Français établis hors de France,10,10ème circonscription,227,Yaounde,1,1514,800,52.84,...,4,0.26,0.56,11,M,FILLON,François,197,13.01,27.71
69239,ZZ,Français établis hors de France,7,7ème circonscription,228,Zagreb,1,655,401,61.22,...,6,0.92,2.39,11,M,FILLON,François,65,9.92,25.90
69240,ZZ,Français établis hors de France,6,6ème circonscription,229,Zurich,1,21477,11129,51.82,...,87,0.41,0.85,11,M,FILLON,François,2893,13.47,28.24
69241,ZZ,Français établis hors de France,11,11ème circonscription,231,Taipeh,1,1204,519,43.11,...,35,2.91,5.18,11,M,FILLON,François,113,9.39,16.72

In [9]:
df_33 = df[df['Code du département']==33]
df_33.columns

Index(['Code du département', 'Libellé du département',
       'Code de la circonscription', 'Libellé de la circonscription',
       'Code de la commune', 'Libellé de la commune', 'Code du b.vote',
       'Inscrits', 'Abstentions', '% Abs/Ins', 'Votants', '% Vot/Ins',
       'Blancs', '% Blancs/Ins', '% Blancs/Vot', 'Nuls', '% Nuls/Ins',
       '% Nuls/Vot', 'Exprimés', '% Exp/Ins', '% Exp/Vot', 'N°Panneau', 'Sexe',
       'Nom', 'Prénom', 'Voix', '% Voix/Ins', '% Voix/Exp', 'N°Panneau.1',
       'Sexe.1', 'Nom.1', 'Prénom.1', 'Voix.1', '% Voix/Ins.1', '% Voix/Exp.1',
       'N°Panneau.2', 'Sexe.2', 'Nom.2', 'Prénom.2', 'Voix.2', '% Voix/Ins.2',
       '% Voix/Exp.2', 'N°Panneau.3', 'Sexe.3', 'Nom.3', 'Prénom.3', 'Voix.3',
       '% Voix/Ins.3', '% Voix/Exp.3', 'N°Panneau.4', 'Sexe.4', 'Nom.4',
       'Prénom.4', 'Voix.4', '% Voix/Ins.4', '% Voix/Exp.4', 'N°Panneau.5',
       'Sexe.5', 'Nom.5', 'Prénom.5', 'Voix.5', '% Voix/Ins.5', '% Voix/Exp.5',
       'N°Panneau.6', 'Sexe.6', 'Nom.6', 'Prénom.6', 'Voix.6', '% Voix/Ins.6',
       '% Voix/Exp.6', 'N°Panneau.7', 'Sexe.7', 'Nom.7', 'Prénom.7', 'Voix.7',
       '% Voix/Ins.7', '% Voix/Exp.7', 'N°Panneau.8', 'Sexe.8', 'Nom.8',
       'Prénom.8', 'Voix.8', '% Voix/Ins.8', '% Voix/Exp.8', 'N°Panneau.9',
       'Sexe.9', 'Nom.9', 'Prénom.9', 'Voix.9', '% Voix/Ins.9', '% Voix/Exp.9',
       'N°Panneau.10', 'Sexe.10', 'Nom.10', 'Prénom.10', 'Voix.10',
       '% Voix/Ins.10', '% Voix/Exp.10'],
      dtype='object')

In [12]:
df_33[df_33[['Code de la circonscription', 'Code du b.vote']].duplicated()]

,Code du département,Libellé du département,Code de la circonscription,Libellé de la circonscription,Code de la commune,Libellé de la commune,Code du b.vote,Inscrits,Abstentions,% Abs/Ins,...,Voix.9,% Voix/Ins.9,% Voix/Exp.9,N°Panneau.10,Sexe.10,Nom.10,Prénom.10,Voix.10,% Voix/Ins.10,% Voix/Exp.10
20325,33,Gironde,4,4ème circonscription,4,Ambès,0001,916,226,24.67,...,4,0.44,0.59,11,M,FILLON,François,48,5.24,7.08
20326,33,Gironde,4,4ème circonscription,4,Ambès,0002,765,230,30.07,...,6,0.78,1.15,11,M,FILLON,François,65,8.50,12.50
20327,33,Gironde,4,4ème circonscription,4,Ambès,0003,529,130,24.57,...,5,0.95,1.30,11,M,FILLON,François,18,3.40,4.69
20339,33,Gironde,11,11ème circonscription,6,Anglade,0001,671,124,18.48,...,12,1.79,2.23,11,M,FILLON,François,61,9.09,11.36
20341,33,Gironde,12,12ème circonscription,8,Arbis,0001,202,35,17.33,...,1,0.50,0.63,11,M,FILLON,François,32,15.84,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21661,33,Gironde,4,4ème circonscription,554,Yvrac,0002,1068,161,15.07,...,11,1.03,1.24,11,M,FILLON,François,205,19.19,23.03
21662,33,Gironde,8,8ème circonscription,555,Marcheprime,0001,1078,209,19.39,...,10,0.93,1.18,11,M,FILLON,François,99,9.18,11.69
21663,33,Gironde,8,8ème circonscription,555,Marcheprime,0002,1187,193,16.26,...,9,0.76,0.94,11,M,FILLON,François,94,7.92,9.80
21664,33,Gironde,8,8ème circonscription,555,Marcheprime,0003,868,120,13.82,...,8,0.92,1.11,11,M,FILLON,François,90,10.37,12.45
21665,33,Gironde,8,8ème circonscription,555,Marcheprime,0004,432,90,20.83,...,3,0.69,0.91,11,M,FILLON,François,31,7.18,9.37

In [13]:
df_33[df_33[['Code de la commune', 'Code du b.vote']].duplicated()]

Empty DataFrame
Columns: [Code du département, Libellé du département, Code de la circonscription, Libellé de la circonscription, Code de la commune, Libellé de la commune, Code du b.vote, Inscrits, Abstentions, % Abs/Ins, Votants, % Vot/Ins, Blancs, % Blancs/Ins, % Blancs/Vot, Nuls, % Nuls/Ins, % Nuls/Vot, Exprimés, % Exp/Ins, % Exp/Vot, N°Panneau, Sexe, Nom, Prénom, Voix, % Voix/Ins, % Voix/Exp, N°Panneau.1, Sexe.1, Nom.1, Prénom.1, Voix.1, % Voix/Ins.1, % Voix/Exp.1, N°Panneau.2, Sexe.2, Nom.2, Prénom.2, Voix.2, % Voix/Ins.2, % Voix/Exp.2, N°Panneau.3, Sexe.3, Nom.3, Prénom.3, Voix.3, % Voix/Ins.3, % Voix/Exp.3, N°Panneau.4, Sexe.4, Nom.4, Prénom.4, Voix.4, % Voix/Ins.4, % Voix/Exp.4, N°Panneau.5, Sexe.5, Nom.5, Prénom.5, Voix.5, % Voix/Ins.5, % Voix/Exp.5, N°Panneau.6, Sexe.6, Nom.6, Prénom.6, Voix.6, % Voix/Ins.6, % Voix/Exp.6, N°Panneau.7, Sexe.7, Nom.7, Prénom.7, Voix.7, % Voix/Ins.7, % Voix/Exp.7, N°Panneau.8, Sexe.8, Nom.8, Prénom.8, Voix.8, % Voix/Ins.8, % Voix/Exp.8, N°Panneau.9, Sexe.9, Nom.9, Prénom.9, Voix.9, % Voix/Ins.9, % Voix/Exp.9, N°Panneau.10, Sexe.10, Nom.10, Prénom.10, Voix.10, % Voix/Ins.10, % Voix/Exp.10]
Index: []

[0 rows x 98 columns]

In [5]:
geo = pd.read_csv('../data/raw/geo_bureaux_de_vote.csv')
geo.shape

(70042, 22)

In [6]:
postal = geo['code_postal'].fillna('00')
boo = postal.apply(lambda x : True if x.startswith('33') else False)
np.isin(True, boo)
geo_33 = geo[boo]
geo_33.shape

(1318, 22)

In [7]:
geo_33.columns

Index(['commune_code', 'libelle', 'code', 'libelle.1', 'num_voie', 'voie',
       'complement1', 'complement2', 'lieu_dit', 'code_postal', 'commune',
       'canton_code', 'circonscription_code', 'longitude', 'latitude',
       'geo_score', 'geo_type', 'geo_adresse', 'geo_id', 'geo_ligne', 'geo_l4',
       'geo_l5'],
      dtype='object')

In [15]:
geo_33[geo_33[['commune_code', 'code']].duplicated()]

Empty DataFrame
Columns: [commune_code, libelle, code, libelle.1, num_voie, voie, complement1, complement2, lieu_dit, code_postal, commune, canton_code, circonscription_code, longitude, latitude, geo_score, geo_type, geo_adresse, geo_id, geo_ligne, geo_l4, geo_l5]
Index: []

[0 rows x 22 columns]

In [17]:
duplicates = list()
for circon in geo_33['circonscription_code'].unique():
    #print(circon)
    geo_cir = geo_33[geo_33['circonscription_code']==circon]
    if len(geo_cir['code'].unique()) != len(geo_cir):
        print(circon, " nombre de codes bureaux ", len(geo_cir['code'].unique()), " nombre de bureaux ",len(geo_cir) )
        duplicates.append(abs(len(geo_cir['code'].unique())-len(geo_cir)))

print('total duplicates ', sum(duplicates))

33-08  nombre de codes bureaux  65  nombre de bureaux  117
33-12  nombre de codes bureaux  11  nombre de bureaux  166
33-09  nombre de codes bureaux  21  nombre de bureaux  140
33-06  nombre de codes bureaux  96  nombre de bureaux  116
33-10  nombre de codes bureaux  31  nombre de bureaux  136
33-05  nombre de codes bureaux  42  nombre de bureaux  119
33-11  nombre de codes bureaux  16  nombre de bureaux  121
33-04  nombre de codes bureaux  56  nombre de bureaux  98
33-01  nombre de codes bureaux  91  nombre de bureaux  93
total duplicates  677

In [16]:
geo_33[geo_33[['circonscription_code', 'code']].duplicated()]

,commune_code,libelle,code,libelle.1,num_voie,voie,complement1,complement2,lieu_dit,code_postal,...,circonscription_code,longitude,latitude,geo_score,geo_type,geo_adresse,geo_id,geo_ligne,geo_l4,geo_l5
781,33379,Saint-Brice,1,Mairie de Saint-Brice,NaN,NaN,NaN,NaN,NaN,33540,...,33-12,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN
928,33438,Saint-Maixant,1,SALLE DES FETES,33490,SAINT-MAIXANT,NaN,NaN,NaN,33490,...,33-12,-0.245882,44.581757,0.94,municipality,Saint-Maixant,33438,G,SAINT MAIXANT,NaN
1401,33348,Queyrac,001,FOYER COMMUNAL,NaN,Place DU 11 NOVEMBRE 1918,NaN,NaN,NaN,33340,...,33-05,-0.976556,45.362318,0.80,street,Place du Onze Novembre 1918 33340 Queyrac,33348_0045,G,PLACE DU ONZE NOVEMBRE 1918,NaN
1539,33054,Blaignac,1,MAIRIE DE BLAIGNAC,NaN,LE BOURG,NaN,NaN,NaN,33190,...,33-12,-0.057468,44.552102,0.93,street,Le Bourg 33190 Blaignac,33054_vpswuv,G,LE BOURG,NaN
1560,33363,Sadirac,1,BUREAU DE VOTE 1,NaN,MAIRIE,25 route de Créon,33670 SADIRAC,NaN,33670,...,33-12,-0.401700,44.781151,0.52,street,Lot la Maisonneraie de Pomadis 33670 Sadirac,33363_a064,G,LOT LA MAISONNERAIE DE POMADIS,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69533,33009,Arcachon,02,ECOLE OSIRIS,80,cours Tartas,ECOLE OSIRIS,NaN,NaN,33120,...,33-08,-1.174638,44.660644,0.95,housenumber,80 Cours Tartas 33120 Arcachon,33009_2170_00080,G,80 COURS TARTAS,NaN
69671,33009,Arcachon,01,HOTEL DE VILLE,NaN,Place Lucien de Gracia,HOTEL DE VILLE,NaN,NaN,33120,...,33-08,-1.170577,44.660989,0.95,street,Place Lucien de Gracia 33120 Arcachon,33009_1358,G,PLACE LUCIEN DE GRACIA,NaN
69724,33033,Baurech,1,Bureau 1,NaN,Mairie,NaN,NaN,NaN,33880,...,33-12,-0.419674,44.737937,0.65,street,La Metairie 33880 Baurech,33033_27fj2b,G,LA METAIRIE,NaN
69816,33339,Prignac-et-Marcamps,001,BUREAU DE VOTE 1,85,Avenue Côtes de Bourg,MAIRIE,NaN,NaN,33710,...,33-11,-0.491712,45.032520,0.90,housenumber,85 Avenue des Côtes de Bourg 33710 Prignac-et-...,33339_0190_00085,G,85 AVENUE DES COTES DE BOURG,NaN
70008,33082,Cadillac-en-Fronsadais,1,BUREAU N° 1,NaN,NaN,NaN,NaN,NaN,33240,...,33-10,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
geo_33[geo_33[['commune_code', 'code']].duplicated()]

Empty DataFrame
Columns: [commune_code, libelle, code, libelle.1, num_voie, voie, complement1, complement2, lieu_dit, code_postal, commune, canton_code, circonscription_code, longitude, latitude, geo_score, geo_type, geo_adresse, geo_id, geo_ligne, geo_l4, geo_l5]
Index: []

[0 rows x 22 columns]

On veut savoir si l'on peut retrouver la même nomenclature pour les codes communes dans un base de données et dans l'autre

In [24]:
df_33[['Code de la commune', 'Libellé de la commune']]

       Code de la commune Libellé de la commune
20311                   1                 Abzac
20312                   1                 Abzac
20313                   2                Aillas
20314                   3    Ambarès-et-Lagrave
20315                   3    Ambarès-et-Lagrave
...                   ...                   ...
21661                 554                 Yvrac
21662                 555           Marcheprime
21663                 555           Marcheprime
21664                 555           Marcheprime
21665                 555           Marcheprime

[1355 rows x 2 columns]

In [45]:
df_33_communes = pd.DataFrame({'Code de la commune' : list(df_33['Code de la commune'].apply(lambda x : str(x + 33000)).unique()), 'Libellé de la commune' : list(df_33['Libellé de la commune'].unique())})
df_33_communes

    Code de la commune Libellé de la commune
0                33001                 Abzac
1                33002                Aillas
2                33003    Ambarès-et-Lagrave
3                33004                 Ambès
4                33005    Andernos-les-Bains
..                 ...                   ...
533              33551            Villeneuve
534              33552              Virelade
535              33553                Virsac
536              33554                 Yvrac
537              33555           Marcheprime

[538 rows x 2 columns]

In [39]:
geo_33_communes = pd.DataFrame({'Code de la commune' : list(geo_33['commune_code'].unique()), 'Libellé de la commune' : list(geo_33['libelle'].unique())})
geo_33_communes

    Code de la commune   Libellé de la commune
0                33529        La Teste-de-Buch
1                33318                  Pessac
2                33263                 Madirac
3                33076                   Budos
4                33281                Mérignac
..                 ...                     ...
495              33186                  Gensac
496              33500                 Samonac
497              33033                 Baurech
498              33339     Prignac-et-Marcamps
499              33082  Cadillac-en-Fronsadais

[500 rows x 2 columns]

In [40]:
geo_33[geo_33['libelle'].isna()]

Empty DataFrame
Columns: [commune_code, libelle, code, libelle.1, num_voie, voie, complement1, complement2, lieu_dit, code_postal, commune, canton_code, circonscription_code, longitude, latitude, geo_score, geo_type, geo_adresse, geo_id, geo_ligne, geo_l4, geo_l5]
Index: []

[0 rows x 22 columns]

In [41]:
geo_33[geo_33['commune_code'].isna()]

Empty DataFrame
Columns: [commune_code, libelle, code, libelle.1, num_voie, voie, complement1, complement2, lieu_dit, code_postal, commune, canton_code, circonscription_code, longitude, latitude, geo_score, geo_type, geo_adresse, geo_id, geo_ligne, geo_l4, geo_l5]
Index: []

[0 rows x 22 columns]

In [49]:
test_same_communes = pd.merge(geo_33_communes, df_33_communes, left_on = ['Code de la commune', 'Libellé de la commune'], right_on = ['Code de la commune', 'Libellé de la commune'])
test_same_communes

    Code de la commune   Libellé de la commune
0                33529        La Teste-de-Buch
1                33318                  Pessac
2                33263                 Madirac
3                33076                   Budos
4                33281                Mérignac
..                 ...                     ...
484              33186                  Gensac
485              33500                 Samonac
486              33033                 Baurech
487              33339     Prignac-et-Marcamps
488              33082  Cadillac-en-Fronsadais

[489 rows x 2 columns]

In [54]:
test_same_communes = pd.merge(geo_33_communes, df_33_communes, left_on = 'Code de la commune', right_on = 'Code de la commune')
test_same_communes

    Code de la commune Libellé de la commune_x Libellé de la commune_y
0                33529        La Teste-de-Buch        La Teste-de-Buch
1                33318                  Pessac                  Pessac
2                33263                 Madirac                 Madirac
3                33076                   Budos                   Budos
4                33281                Mérignac                Mérignac
..                 ...                     ...                     ...
495              33186                  Gensac                  Gensac
496              33500                 Samonac                 Samonac
497              33033                 Baurech                 Baurech
498              33339     Prignac-et-Marcamps     Prignac-et-Marcamps
499              33082  Cadillac-en-Fronsadais  Cadillac-en-Fronsadais

[500 rows x 3 columns]

In [64]:
test_same_communes['different'] = np.where(test_same_communes['Libellé de la commune_x'] != test_same_communes['Libellé de la commune_y'], True, False)
test_same_communes

,Code de la commune,Libellé de la commune_x,Libellé de la commune_y,different
0,33529,La Teste-de-Buch,La Teste-de-Buch,False
1,33318,Pessac,Pessac,False
2,33263,Madirac,Madirac,False
3,33076,Budos,Budos,False
4,33281,Mérignac,Mérignac,False
...,...,...,...,...
495,33186,Gensac,Gensac,False
496,33500,Samonac,Samonac,False
497,33033,Baurech,Baurech,False
498,33339,Prignac-et-Marcamps,Prignac-et-Marcamps,False
499,33082,Cadillac-en-Fronsadais,Cadillac-en-Fronsadais,False

In [65]:
test_same_communes[test_same_communes['different']]

,Code de la commune,Libellé de la commune_x,Libellé de la commune_y,different
51,33008,Porte-de-Benauge,Arbis,True
104,33106,Castets et Castillon,Castets-et-Castillon,True
150,33396,Saint-Étienne-de-Lisse,Saint-Etienne-de-Lisse,True
169,33259,Lugon-et-l'Île-du-Carnay,Lugon-et-l'Ile-du-Carnay,True
191,33394,Saint-Émilion,Saint-Emilion,True
217,33154,Les Églisottes-et-Chalaures,Les Eglisottes-et-Chalaures,True
323,33055,Blaignan-Prignac,Blaignan,True
325,33380,Val-de-Livenne,Saint-Caprais-de-Blaye,True
369,33159,Étauliers,Etauliers,True
398,33496,Sallebœuf,Salleboeuf,True
423,33018,Val de Virvée,Val-de-Virvée,True

Nous pouvons utiliser la juxtaposition du code commune et bureau de vote pour établir la fusion des deux bases de données au sein du département de Gironde (33)

In [71]:
df_33['Code du b.vote'].unique()

array(['0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008',
       '0009', '0010', '0011', '0012', '0013', '0014', '0015', '0016',
       '2301', '2302', '2303', '2304', '3201', '3202', '3203', '3204',
       '3205', '3206', '3301', '3302', '3303', '3304', '3401', '3402',
       '3403', '3404', '3405', '3501', '3502', '3503', '3504', '3505',
       '3506', '3601', '3602', '3603', '3604', '3605', '3606', '4101',
       '4102', '4103', '4104', '4201', '4202', '4203', '4204', '4301',
       '4302', '4401', '4402', '4403', '4501', '4502', '4601', '4602',
       '4701', '4702', '4703', '4801', '4802', '4803', '4804', '4901',
       '4902', '4903', '4904', '1101', '1102', '1201', '1202', '1203',
       '1301', '1302', '1303', '1401', '1402', '1403', '1501', '1502',
       '1503', '1601', '1602', '1603', '1604', '1701', '1702', '1801',
       '1802', '2101', '2102', '2201', '2202', '2203', '2204', '2401',
       '2402', '2403', '2404', '2405', '2406', '2407', '2501', '2502',
       '2503', '2601', '2602', '2603', '2701', '2702', '2703', '2704',
       '3101', '3102', '3103', '3104', '5105', '5301', '5302', '5601',
       '5602', '5603', '5701', '5702', '5801', '5802', '5901', '5902',
       '5903', '5101', '5102', '5103', '5104', '5201', '5202', '5203',
       '5303', '5304', '5305', '5401', '5402', '5403', '5501', '5502',
       '0017', '0018', '0019', '0020', '0021', '0022', '0023', '0024',
       '0025', '0026', '0027', '0028', '0050', '0051', '0052', '0053',
       '0054', '0055', '0056', '0057', '0058', '0059', '0060', '0061',
       '0062', '0063', '0064', '0065', '0066', '0067', '0068', '0069',
       '0070', '0071', '0029', '0030', '0031', '0032', '0033', '0034',
       '0035', '0036', '0037', '0038', '0039', '0040', '0041', '0042'],
      dtype=object)

In [72]:
geo_33['code'].unique()

array(['001', '019', '1', '002', '016', '003', '020', '01B', '0005',
       '008', '068', '03C', '069', '4', '6', '007', '2', '7', '3', '006',
       '014', '012', '02A', '2801', '5', '10', '8', '01A', '9', '4503',
       '0015', '024', '027', '0004', '05', '1 ', '0023', '0006', '0007',
       '023', '0008', '004', '01', '005', '0017', '021', '502', '505',
       '03D', '009', '2101', '017', '018', '011', '03', '010', '0001',
       '02', '013', '00008', '1 - 2', '06C', '5503', '032', '05C', '1404',
       '1504', '04B', '0003', '031', '0009', '1605', '03B', '015', '1101',
       '2705', '066', '028', '0014', '04D', '5201', '02C', '5602', '022',
       '501', '0002', '0016', '503', '5102', '03A', '0010', '0011',
       '2503', '0013', '504', '0018', '0019', '0012', '0020', '1202',
       '0021', '1702', '0022', '0024', '0025', '3102', '11', '04A',
       '1302', '00004', '025', '1303', '1102', '1201', '4501', '00007',
       '1203', '1301', '3605', '1401', '1402', '1403', '1501', '1503',
       '052', '1601', '1604', '1801', '1802', '2102', '2201', '2301',
       '2302', '2303', '2803', '2304', '2402', '2403', '2404', '2405',
       '2406', '2601', '2501', '2504', '2602', '2603', '3101', '3201',
       '3203', '3204', '061', '3302', '3303', '3401', '063', '3402',
       '065', '3405', '3503', '3504', '3603', '04', '3601', '3604', '070',
       '3606', '3702', '072', '08', '3704', '4101', '4102', '073', '506',
       '4103', '054', '4104', '4701', '4201', '4202', '4203', '055',
       '02-1', '4204', '4302', '4303', '4401', '4402', '1 - 1', '4403',
       '4601', '4602', '4603', '4702', '4703', '4801', '4802', '06',
       '4803', '07', '4804', '4901', '4904', '4902', '4903', '09', '01-1',
       '5101', '5103', '5104', '5105', '1502', '5203', '5301', '5302',
       '067', '5303', '5304', '5305', '029', '5401', '01 - 1', '5402',
       '5403', '1602', '2701', '1603', '5501', '1701', '5502', '5601',
       '5603', '050', '5701', '026', '5901', '5902', '5903', '051', '037',
       '053', '039', '041', '033', '042', '030', '2502', '034', '2702',
       '035', '036', '058', '059', '057', '056', '01D', '03E', '060',
       '01C', '02B', '02D', '04C', '062', '05A', '01E', '2703', '2704',
       '064', '3104', '3103', '3301', '3304', '3403', '3404', '3502',
       '3505', '3602', '01 ', '4502', '4301', '5202', '5702', '5801',
       '5802', '00002', '00006', '05B', '06A', '07A', '08A', '0026',
       '071', '00005', '00001', '00003', '00009', '1LC', '12', '14',
       '2202', '2203', '3701', '2802', '3501', '2401', '3703', '3202',
       '040', '038', '13'], dtype=object)

Nous devons homogénéiser la longueur du code bureaux de vote dans geo_33

In [66]:
df_merge = df_33['Code de la commune'].apply(lambda x : str(x + 33000)) +'_' + df_33['Code du b.vote']
df_33[df_merge.duplicated()]

Empty DataFrame
Columns: [Code du département, Libellé du département, Code de la circonscription, Libellé de la circonscription, Code de la commune, Libellé de la commune, Code du b.vote, Inscrits, Abstentions, % Abs/Ins, Votants, % Vot/Ins, Blancs, % Blancs/Ins, % Blancs/Vot, Nuls, % Nuls/Ins, % Nuls/Vot, Exprimés, % Exp/Ins, % Exp/Vot, N°Panneau, Sexe, Nom, Prénom, Voix, % Voix/Ins, % Voix/Exp, N°Panneau.1, Sexe.1, Nom.1, Prénom.1, Voix.1, % Voix/Ins.1, % Voix/Exp.1, N°Panneau.2, Sexe.2, Nom.2, Prénom.2, Voix.2, % Voix/Ins.2, % Voix/Exp.2, N°Panneau.3, Sexe.3, Nom.3, Prénom.3, Voix.3, % Voix/Ins.3, % Voix/Exp.3, N°Panneau.4, Sexe.4, Nom.4, Prénom.4, Voix.4, % Voix/Ins.4, % Voix/Exp.4, N°Panneau.5, Sexe.5, Nom.5, Prénom.5, Voix.5, % Voix/Ins.5, % Voix/Exp.5, N°Panneau.6, Sexe.6, Nom.6, Prénom.6, Voix.6, % Voix/Ins.6, % Voix/Exp.6, N°Panneau.7, Sexe.7, Nom.7, Prénom.7, Voix.7, % Voix/Ins.7, % Voix/Exp.7, N°Panneau.8, Sexe.8, Nom.8, Prénom.8, Voix.8, % Voix/Ins.8, % Voix/Exp.8, N°Panneau.9, Sexe.9, Nom.9, Prénom.9, Voix.9, % Voix/Ins.9, % Voix/Exp.9, N°Panneau.10, Sexe.10, Nom.10, Prénom.10, Voix.10, % Voix/Ins.10, % Voix/Exp.10]
Index: []

[0 rows x 98 columns]

In [68]:
df_33['merge'] = df_merge
df_33

/home/will/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,Code du département,Libellé du département,Code de la circonscription,Libellé de la circonscription,Code de la commune,Libellé de la commune,Code du b.vote,Inscrits,Abstentions,% Abs/Ins,...,% Voix/Ins.9,% Voix/Exp.9,N°Panneau.10,Sexe.10,Nom.10,Prénom.10,Voix.10,% Voix/Ins.10,% Voix/Exp.10,merge
20311,33,Gironde,11,11ème circonscription,1,Abzac,0001,735,182,24.76,...,0.14,0.18,11,M,FILLON,François,50,6.80,9.23,33001_0001
20312,33,Gironde,11,11ème circonscription,1,Abzac,0002,742,189,25.47,...,0.67,0.93,11,M,FILLON,François,69,9.30,12.87,33001_0002
20313,33,Gironde,12,12ème circonscription,2,Aillas,0001,598,96,16.05,...,0.84,1.04,11,M,FILLON,François,95,15.89,19.75,33002_0001
20314,33,Gironde,4,4ème circonscription,3,Ambarès-et-Lagrave,0001,741,170,22.94,...,0.54,0.72,11,M,FILLON,François,69,9.31,12.37,33003_0001
20315,33,Gironde,4,4ème circonscription,3,Ambarès-et-Lagrave,0002,1026,225,21.93,...,1.17,1.53,11,M,FILLON,François,74,7.21,9.43,33003_0002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21661,33,Gironde,4,4ème circonscription,554,Yvrac,0002,1068,161,15.07,...,1.03,1.24,11,M,FILLON,François,205,19.19,23.03,33554_0002
21662,33,Gironde,8,8ème circonscription,555,Marcheprime,0001,1078,209,19.39,...,0.93,1.18,11,M,FILLON,François,99,9.18,11.69,33555_0001
21663,33,Gironde,8,8ème circonscription,555,Marcheprime,0002,1187,193,16.26,...,0.76,0.94,11,M,FILLON,François,94,7.92,9.80,33555_0002
21664,33,Gironde,8,8ème circonscription,555,Marcheprime,0003,868,120,13.82,...,0.92,1.11,11,M,FILLON,François,90,10.37,12.45,33555_0003
21665,33,Gironde,8,8ème circonscription,555,Marcheprime,0004,432,90,20.83,...,0.69,0.91,11,M,FILLON,François,31,7.18,9.37,33555_0004

#### Creation de la colonne de fusion pour la base de données géographique

In [70]:
geo_merge = geo_33['commune_code']+'_'+geo_33['code'].apply(lambda x : '0'+x if len(x) ==3 else '00'+x if len(x)==2 else '000'+x if len(x) ==1 else x)
geo_33[geo_merge.duplicated()]

,commune_code,libelle,code,libelle.1,num_voie,voie,complement1,complement2,lieu_dit,code_postal,...,circonscription_code,longitude,latitude,geo_score,geo_type,geo_adresse,geo_id,geo_ligne,geo_l4,geo_l5
13121,33106,Castets et Castillon,01,CASTETS EN DORTHE (Caduque),28,Grand rue,NaN,NaN,MAIRIE,33210,...,33-09,-0.155228,44.559989,0.50,housenumber,28 Rue Grossolle 33210 Castets et Castillon,33106_0040_00028,G,28 RUE GROSSOLLE,NaN
34892,33106,Castets et Castillon,2,CASTILLON-DE-CASTETS,16,LE BOURG,NaN,NaN,CASTILLON DE CASTETS,33210,...,33-12,-0.153722,44.560988,0.94,street,Le Bourg 33210 Castets et Castillon,33106_pj2eeq,G,LE BOURG,NaN
54492,33511,Sendets,1,MAIRIE,NaN,Le Bourg,33690 SENDETS,NaN,NaN,33690,...,33-09,-0.085949,44.423520,0.93,street,Le Bourg 33690 Sendets,33511_fcz7n2,G,LE BOURG,NaN
54805,33179,Galgon,01,SALLE DES FÊTES,NaN,Avenue FRANCOIS MITTERRAND,NaN,NaN,NaN,33133,...,33-10,-0.274936,44.991607,0.88,street,Avenue Francois Mitterand 33133 Galgon,33179_0320,G,AVENUE FRANCOIS MITTERAND,NaN
66851,33137,Cours-les-Bains,1,MAIRIE,NaN,Le Bourg,33690 COURS LES BAINS,NaN,NaN,33690,...,33-09,0.015131,44.368767,0.71,street,Le Bourdat 33690 Cours-les-Bains,33137_6heqze,G,LE BOURDAT,NaN

In [74]:
geo_33['merge'] = geo_merge
geo_33

/home/will/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,commune_code,libelle,code,libelle.1,num_voie,voie,complement1,complement2,lieu_dit,code_postal,...,longitude,latitude,geo_score,geo_type,geo_adresse,geo_id,geo_ligne,geo_l4,geo_l5,merge
355,33529,La Teste-de-Buch,001,THEATRE PIERRE CRAVEY 1,NaN,Rue Gilbert Sore,NaN,NaN,NaN,33260,...,-1.150775,44.631127,0.95,street,Rue Gilbert Sore 33260 La Teste-de-Buch,33529_1343,G,RUE GILBERT SORE,NaN,33529_0001
379,33318,Pessac,019,ECOLE MAGONTY,3,PLACE DE LA RESISTANCE,NaN,NaN,NaN,33600,...,-0.704864,44.792797,0.96,housenumber,3 Place de la Résistance 33600 Pessac,33318_2937_00003,G,3 PLACE DE LA RESISTANCE,NaN,33318_0019
420,33263,Madirac,1,MAIRIE,2,Route de Haux,33670 MADIRAC,NaN,NaN,33670,...,-0.399678,44.759930,0.93,housenumber,2 Route de Haux 33670 Madirac,33263_2000_00002,G,2 ROUTE DE HAUX,NaN,33263_0001
458,33529,La Teste-de-Buch,002,THEATRE PIERRE CRAVEY 2,NaN,Rue Gilbert Sore,NaN,NaN,NaN,33260,...,-1.150775,44.631127,0.95,street,Rue Gilbert Sore 33260 La Teste-de-Buch,33529_1343,G,RUE GILBERT SORE,NaN,33529_0002
563,33076,Budos,1,SALLE LATAPY,5,Rue du Château,33720 BUDOS,NaN,NaN,33720,...,-0.384930,44.534274,0.94,housenumber,5 Rue du Chateau 33720 Budos,33076_0100_00005,G,5 RUE DU CHATEAU,NaN,33076_0001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69534,33009,Arcachon,11,ECOLE DU MOULLEAU,NaN,Avenue Louis Garros,ECOLE DU MOULLEAU,NaN,NaN,33120,...,-1.199907,44.643033,0.95,street,Avenue Louis Garros 33120 Arcachon,33009_1330,G,AVENUE LOUIS GARROS,NaN,33009_0011
69671,33009,Arcachon,01,HOTEL DE VILLE,NaN,Place Lucien de Gracia,HOTEL DE VILLE,NaN,NaN,33120,...,-1.170577,44.660989,0.95,street,Place Lucien de Gracia 33120 Arcachon,33009_1358,G,PLACE LUCIEN DE GRACIA,NaN,33009_0001
69724,33033,Baurech,1,Bureau 1,NaN,Mairie,NaN,NaN,NaN,33880,...,-0.419674,44.737937,0.65,street,La Metairie 33880 Baurech,33033_27fj2b,G,LA METAIRIE,NaN,33033_0001
69816,33339,Prignac-et-Marcamps,001,BUREAU DE VOTE 1,85,Avenue Côtes de Bourg,MAIRIE,NaN,NaN,33710,...,-0.491712,45.032520,0.90,housenumber,85 Avenue des Côtes de Bourg 33710 Prignac-et-...,33339_0190_00085,G,85 AVENUE DES COTES DE BOURG,NaN,33339_0001
70008,33082,Cadillac-en-Fronsadais,1,BUREAU N° 1,NaN,NaN,NaN,NaN,NaN,33240,...,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,33082_0001

In [75]:
geo_to_merge = geo_33[['merge', 'latitude', 'longitude', 'geo_adresse']]
geo_to_merge

,merge,latitude,longitude,geo_adresse
355,33529_0001,44.631127,-1.150775,Rue Gilbert Sore 33260 La Teste-de-Buch
379,33318_0019,44.792797,-0.704864,3 Place de la Résistance 33600 Pessac
420,33263_0001,44.759930,-0.399678,2 Route de Haux 33670 Madirac
458,33529_0002,44.631127,-1.150775,Rue Gilbert Sore 33260 La Teste-de-Buch
563,33076_0001,44.534274,-0.384930,5 Rue du Chateau 33720 Budos
...,...,...,...,...
69534,33009_0011,44.643033,-1.199907,Avenue Louis Garros 33120 Arcachon
69671,33009_0001,44.660989,-1.170577,Place Lucien de Gracia 33120 Arcachon
69724,33033_0001,44.737937,-0.419674,La Metairie 33880 Baurech
69816,33339_0001,45.032520,-0.491712,85 Avenue des Côtes de Bourg 33710 Prignac-et-...
70008,33082_0001,NaN,NaN,NaN

In [76]:
file33 = pd.merge(df_33, geo_to_merge, left_on='merge', right_on = 'merge')
file33 = file33.dropna()
file33

,Code du département,Libellé du département,Code de la circonscription,Libellé de la circonscription,Code de la commune,Libellé de la commune,Code du b.vote,Inscrits,Abstentions,% Abs/Ins,...,Sexe.10,Nom.10,Prénom.10,Voix.10,% Voix/Ins.10,% Voix/Exp.10,merge,latitude,longitude,geo_adresse
0,33,Gironde,11,11ème circonscription,1,Abzac,0001,735,182,24.76,...,M,FILLON,François,50,6.80,9.23,33001_0001,45.012819,-0.136758,1 Le Paradis 33230 Abzac
1,33,Gironde,11,11ème circonscription,1,Abzac,0002,742,189,25.47,...,M,FILLON,François,69,9.30,12.87,33001_0002,45.015601,-0.127377,Rue du Pétreau 33230 Abzac
3,33,Gironde,4,4ème circonscription,3,Ambarès-et-Lagrave,0001,741,170,22.94,...,M,FILLON,François,69,9.31,12.37,33003_0001,44.926443,-0.490388,18 Place de la Victoire 33440 Ambarès-et-Lagrave
4,33,Gironde,4,4ème circonscription,3,Ambarès-et-Lagrave,0002,1026,225,21.93,...,M,FILLON,François,74,7.21,9.43,33003_0002,44.924868,-0.497058,Avenue de l'Europe 33440 Ambarès-et-Lagrave
5,33,Gironde,4,4ème circonscription,3,Ambarès-et-Lagrave,0003,950,184,19.37,...,M,FILLON,François,84,8.84,11.11,33003_0003,44.935118,-0.487910,Rue Lamartine 33440 Ambarès-et-Lagrave
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1177,33,Gironde,11,11ème circonscription,553,Virsac,0001,681,137,20.12,...,M,FILLON,François,68,9.99,12.81,33553_0001,45.027210,-0.441056,105 Route de la Mairie 33240 Virsac
1178,33,Gironde,4,4ème circonscription,554,Yvrac,0001,946,173,18.29,...,M,FILLON,François,130,13.74,17.38,33554_0001,44.880837,-0.465589,Allée des Roses 33370 Yvrac
1179,33,Gironde,4,4ème circonscription,554,Yvrac,0002,1068,161,15.07,...,M,FILLON,François,205,19.19,23.03,33554_0002,44.880837,-0.465589,Allée des Roses 33370 Yvrac
1180,33,Gironde,8,8ème circonscription,555,Marcheprime,0001,1078,209,19.39,...,M,FILLON,François,99,9.18,11.69,33555_0001,44.698392,-0.840787,Allée des Violettes 33380 Marcheprime
1181,33,Gironde,8,8ème circonscription,555,Marcheprime,0002,1187,193,16.26,...,M,FILLON,François,94,7.92,9.80,33555_0002,44.698392,-0.840787,Allée des Violettes 33380 Marcheprime